services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      MONGO_URI: "mongodb+srv://naveenselvan0004_db_user:33wh5wKQDLXGGUYa@cluster0.si9nfr3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MONGO_DB_NAME: "polling_app"
      REDIS_ADDR: "redis:6379"
      JWT_SECRET: "local-development-secret-change-me"
      JWT_EXPIRY_HOURS: "24"
      BCRYPT_COST: "11"
      FRONTEND_BASE_URL: "https://polling.naveenselvan.me,https://realtime-polling-app-blond.vercel.app,http://localhost:5173"
      COOKIE_SECURE: "true"
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  redis_data:
