import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../lib/api'
import { formatDate, formatTimeLeft } from '../lib/format'
import { Loading } from '../components/Loading'
import { LiveMark, Shell } from '../components/Shell'
import { Results } from '../components/Results'
import { usePoll } from '../lib/usePoll'
import { SharePoll } from '../components/SharePoll'

export function PollPage(){const {id=''}=useParams();const {poll,setPoll,loading,error,connection,notice}=usePoll(id);const [selected,setSelected]=useState('');const [voting,setVoting]=useState(false);const [voteError,setVoteError]=useState('');if(loading)return <Shell minimal><Loading label="Finding the room"/></Shell>;if(error||!poll)return <Shell minimal><div className="not-found"><span className="section-label">404 / no signal</span><h1>This room isn’t here.</h1><p>{error||'The poll may have moved, or the link may be incomplete.'}</p><Link className="primary-button" to="/">Back to signal</Link></div></Shell>;
  async function vote(){if(!selected)return;setVoting(true);setVoteError('');try{const result=await api.vote(id,selected);setPoll((current)=>current?{...current,hasVoted:true,results:result.counts}:current)}catch(caught){setVoteError(caught instanceof Error?caught.message:'Your vote could not be counted.')}finally{setVoting(false)}}
  return <Shell minimal><div className="poll-page"><div className="poll-context"><Link className="back-link" to="/">← Signal Polls</Link><LiveMark status={connection}/></div><section className="poll-hero"><div className="poll-hero-meta"><span className={`status-chip status-${poll.status}`}>{poll.status==='open'?'Open for votes':'Closed'}</span><span className="mono">{formatDate(poll.createdAt)} · {formatTimeLeft(poll.expiresAt)}</span></div><h1>{poll.question}</h1><p className="poll-helper">{poll.status==='closed'?'The room is closed. See where the answer landed.':poll.hasVoted?'Your answer is in. Watch the room move.':'Choose one answer. You can change the room, not your vote.'}</p><SharePoll poll={poll} /></section>{notice&&<div className="notice-banner" role="status">{notice}</div>}{poll.status==='open'&&!poll.hasVoted?<section className="vote-panel"><div className="section-heading"><span className="section-label">Your answer</span><span className="mono">ONE RESPONSE</span></div><div className="vote-options" role="radiogroup" aria-label="Poll options">{poll.options.map((option)=><label className={`vote-option ${selected===option.id?'is-selected':''}`} key={option.id}><input type="radio" name="poll-option" value={option.id} checked={selected===option.id} onChange={()=>setSelected(option.id)}/><span className="radio-mark" aria-hidden="true" /><span>{option.text}</span></label>)}</div>{voteError&&<div className="error-banner" role="alert">{voteError}</div>}<button className="primary-button vote-button" disabled={!selected||voting} onClick={vote}>{voting?'Counting your answer…':'Cast my vote'} <span aria-hidden="true">↗</span></button></section>:<Results poll={poll}/>}<div className="poll-footnote"><span className="mono">ROOM ID / {poll.id.slice(0,8).toUpperCase()}</span><span>Results update live for everyone in the room.</span></div></div></Shell>}
